### ISSUE TITLE
Update OS Call WIki Page for June 27th

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#175]
You will need to sign up for a mozilla wiki account.  

[On this wiki page ](https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors#D.26I_in_Open_Source_Community_Calls)  

1. Please move June 6th call information, from under 'future calls' to 'past calls'.
2.  Please link the June 27th call [to this page ](https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors/DI_Call_06_27_2018#June_27.2C_2018_-_Inclusive_Open_Source_Governance)

**Comment by drashti4** [comment]
Done

**Comment by emmairwin** [comment]
HI @drashti4   thanks for moving June 6th under future calls.
The June 27th link is still not there though?
![diversity_and_inclusion_for_communities_and_contributors_-_mozillawiki_-_2018-06-11_09 08 16](https://user-images.githubusercontent.com/60618/41243453-08c2cd86-6d57-11e8-836a-661918e5ac39.png)

**Comment by drashti4** [comment]
I updated 27 June link but didn't get you how it relate to #2

**Comment by musingvirtual** [comment]
Hi @drashti4 - 

I believe Emma wants you to edit this page 

https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors#D.26I_in_Open_Source_Community_Calls

so that it links to your new page in the appropriate spot.

Hope that helps!

**Comment by akshitac8** [comment]
Hey, @drashti4 Are you still working on this?

**Comment by drashti4** [comment]
I think Emma already done and date has been changed. July 25th call redirect to [this](https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors/DI_Call_06_27_2018) where date is July 18.
